---
abstract: 'Dancer 2 session storage in secure cookies'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Dancer2: '0.140001'
  File::Spec: '0'
  File::Temp: '0.22'
  HTTP::Date: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  LWP::UserAgent: '0'
  Module::Build: '0.3601'
  Test::More: '0.96'
  Test::TCP: '1.30'
  YAML: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Session-Cookie
provides:
  Dancer2::Session::Cookie:
    file: lib/Dancer2/Session/Cookie.pm
    version: '0.006'
requires:
  Dancer2: '0.140001'
  Dancer2::Core::Role::SessionFactory: '0'
  Dancer2::Core::Types: '0'
  Moo: '0'
  Session::Storage::Secure: '0.010'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/PerlDancer/Dancer2-Session-Cookie/issues
  homepage: http://search.cpan.org/dist/Dancer2-Session-Cookie/
  repository: https://github.com/PerlDancer/Dancer2-Session-Cookie.git
version: '0.006'
x_authority: cpan:YANICK
x_contributors:
  - 'Breno G. de Oliveira <garu@cpan.org>'
  - 'Russell Jenkins <veryrusty@gmail.com>'
  - 'Sawyer X <xsawyerx@cpan.org>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
